name: Build and Push GHCR Image

on:
    push:
        branches:
            - "**"
        tags:
            - "*"

jobs:
    build:
        uses: docker/github-builder/.github/workflows/build.yml@v1
        permissions:
            contents: read
            packages: write
            id-token: write
        with:
            output: image
            push: true
            distribute: true
            setup-qemu: false
            runner: |
                default=ubuntu-24.04
                linux/amd64=ubuntu-24.04
                linux/arm64=ubuntu-24.04-arm
            platforms: linux/amd64,linux/arm64
            context: .
            file: Dockerfile.multiarch
            set-meta-labels: true
            meta-images: ghcr.io/bingxin666/airstations
            meta-tags: |
                type=ref,event=branch
                type=ref,event=tag
                type=sha,prefix=commit-
                type=raw,value=latest
        secrets:
            registry-auths: |
                - registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
